Add new CI check wrapping all other CI checks into one

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -228,3 +228,19 @@ jobs:
             fi
           done
           git diff --exit-code
+
+  ci-status:
+    name: CI Status
+    runs-on: ubuntu-latest
+    needs: [build, lint, lintc, keep-sorted]
+    if: always()
+    steps:
+      - name: Check Status
+        run: |
+          if [[ "${{ needs.build.result }}" != "success" || \
+                "${{ needs.lint.result }}" != "success" || \
+                "${{ needs.lintc.result }}" != "success" || \
+                "${{ needs.keep-sorted.result }}" != "success" ]]; then
+            echo "CI checks failed"
+            exit 1
+          fi
